# models.py
from pymongo import MongoClient
from bson.objectid import ObjectId
from books_data import BOOKS # Import the initial data list
from config import MONGODB_URI, DATABASE_NAME, COLLECTION_NAME

class Book:
    """
    Represents the Book document structure and handles interaction with 
    the MongoDB 'books' collection.
    """
    
    def __init__(self):
        """Initializes MongoDB connection and client."""
        # --- Database Setup ---
        # 1. Connect to MongoDB client
        self.client = MongoClient(MONGODB_URI)
        # 2. Access the database
        self.db = self.client[DATABASE_NAME]
        # 3. Access the collection
        self.collection = self.db[COLLECTION_NAME]
        
        # --- Initial Data Seeding ---
        self._seed_data_if_empty()

    def _seed_data_if_empty(self):
        """
        Reads data from BOOKS (books_data.py) and stores it into MongoDB 
        if the Book collection is empty.
        """
        # Check if the collection is empty
        if self.collection.count_documents({}) == 0:
            print("Book collection is empty. Seeding data from books_data.py...")
            
            # Prepare data for insertion
            # The BOOKS data from Q2(a) already largely matches the document structure.
            # We don't need a strict class constructor for simple MongoDB interaction
            # but we can ensure the fields match the diagram (Book class diagram only shows fields)
            
            # In the books_data.py, 'author' is a string. The diagram shows 'authors: List of str'.
            # We'll adjust the data structure slightly to match the diagram for 'authors' and
            # also ensure we use 'available' and 'copies' fields as required.
            
            books_to_insert = []
            for book in BOOKS:
                # Assuming 'author' in BOOKS is the main author, converting to List[str]
                authors_list = [book.get('author')] if book.get('author') else []
                
                # Create a document matching the structure implied by the diagram and Q2(a) data
                book_document = {
                    # '_id' will be auto-generated by MongoDB
                    'genres': book.get('genres', []),
                    'title': book['title'],
                    'category': book['category'],
                    'url': book.get('url', ''),
                    'description': book.get('description', ''),
                    'authors': authors_list,
                    'pages': book.get('pages', 0),
                    'available': 1, # Hardcoded as per Q2(a)(iii) image
                    'copies': 1,    # Hardcoded as per Q2(a)(iii) image
                    # Keep extra fields used in Q2(a) for image retrieval
                    'image_file': book['image_file'],
                }
                books_to_insert.append(book_document)
            
            # Insert the documents into the collection
            if books_to_insert:
                self.collection.insert_many(books_to_insert)
                print(f"Successfully inserted {len(books_to_insert)} book documents.")
        else:
            print("Book collection already contains data. Skipping seeding.")
            
    def get_all_books(self, category='All'):
        """
        Retrieves all books, sorted by title, optionally filtered by category.
        Returns a list of book documents.
        """
        query = {}
        if category != 'All':
            query['category'] = category
            
        # MongoDB query: Find all matching documents, sort by 'title' ascending (1)
        books_cursor = self.collection.find(query).sort('title', 1)
        
        # Convert the cursor to a list and process for Flask template
        books_list = []
        for book in books_cursor:
            # MongoDB's _id object must be converted to a string for simple use in URLs (Q2(a) used 'id')
            book['id'] = str(book['_id']) 
            
            # The Q2(a) code used 'author' as a string, but the DB stores 'authors' as a list.
            # Convert 'authors' list back to a comma-separated string for templates
            book['author'] = ", ".join(book.get('authors', []))
            
            # Re-convert 'genres' list to a string
            book['genres'] = ", ".join(book.get('genres', []))
            
            books_list.append(book)
            
        return books_list

    def get_book_by_id(self, book_id):
        """
        Retrieves a single book document by its MongoDB ObjectId.
        Returns the book document or None.
        """
        try:
            # Convert string ID from URL to MongoDB ObjectId
            object_id = ObjectId(book_id)
        except Exception:
            return None # Handle invalid ObjectId format
            
        book = self.collection.find_one({'_id': object_id})
        
        if book:
            # Convert ObjectId and List fields for template use, similar to get_all_books
            book['id'] = str(book['_id'])
            book['author'] = ", ".join(book.get('authors', []))
            book['genres'] = ", ".join(book.get('genres', []))
            
        return book

# Global instance of the Book model for use in app.py
book_model = Book()